### ISSUE TITLE
Impossible to send ergo

### ISSUE THREAD

**Issue by Salvo52** [ergoplatform/ergo-wallet-app#102]
I try to send for the second time my ergo wallet on gate's wallet. And now that's doenst works. I have "Could not send transaction" message and when i click on detail that's Say "not enough nanoerg" ? I can't understand.
Thanks for your hello
![Screenshot_20220330-190401](https://user-images.githubusercontent.com/34077017/160900162-893f538b-7929-43d8-be5f-38564d831fc9.jpg)
![Screenshot_20220330-190408](https://user-images.githubusercontent.com/34077017/160900170-344c7e72-0a04-4784-a3a4-ca9cd1836466.jpg)

**Comment by MrStahlfelge** [comment]
Hi, you need to keep a small amount when you keep tokens in your wallet.
