### ISSUE TITLE
QR Code code in Send vs. QR Code icon in main screen for wallet information

### ISSUE THREAD

**Issue by cafebedouin** [ergoplatform/ergo-wallet-app#107]
Clicking into a read-only wallet on Android
Click on the QR sign next to "Show content for"
Scan an Ergodex transaction generated using SAFEW.
Creates a situation where you drop out of the app and android asks if you want to stop the app or wait for it.

Might want to add some kind of error handling for people that think that the QR code will automagically know what you are doing. Because these two look the same but do not work the same.

**Comment by MrStahlfelge** [comment]
Thanks for the report. It is a bug fixed in ddd515efb84cf464d1af030820a4f0452044c1ab - fix is in the next version.
For the time being, scan from send screen or wallet overview. Only ErgoPay is affected, all other types work from the details screen.
