### ISSUE TITLE
Use fiat amount to send/receive funds

### ISSUE THREAD

**Issue by MrStahlfelge** [ergoplatform/ergo-wallet-app#115]
Ergo Wallet App already calcs fiat amounds on send and receive screen.

When fiat amount is set (!= 0), a switch should be implemented to enter a fiat amount and calc the ERG amount to use.
The setting should be saved for the next usage.

**Comment by Armeanio** [comment]
This would be a great feature as a shift toward a p2p point of sale system.

**Comment by MrStahlfelge** [comment]
This will be done together with #116 as the same input fields are affected.
