### ISSUE TITLE
Price data for native tokens

### ISSUE THREAD

**Issue by andrehafner** [ergoplatform/ergo-wallet-app#139]
Some tokens will show pricing and then not show it at another time. From speaking with the dev I think he is pinging the individual pool API which is not updated as often or only updated when trades actually take place (could be more than 24 hours for lesser used coins). The correct API link for real time trade/pricing is this:
https://api.ergodex.io/v1/amm/markets?from=1653075262280
Special thanks to Gazza for helping me with this info when I was building my app. 

Here is a link to how I parse out the dump for the coins I collect info off of ergodex (spectrum) if it helps at all (prob not as it's in perl): https://github.com/andrehafner/my.ergoport.dev/blob/main/priceupdater.pl

**Comment by MrStahlfelge** [comment]
Thank you, checked and the prices seem to be good. Next version will use the magic from parameter.
