### ISSUE TITLE
Support derived addresses from public key on read-only mode

### ISSUE THREAD

**Issue by anon-br** [ergoplatform/ergo-wallet-app#32]
In order to have a smoother experience between the Ergo's wallets, it would be great if a way to derive addresses from the wallet's Extended Public Key was implemented by reading its QR Code.

* Yoroi provides the public key at Settings > Wallet > Export.
* [Ergo Paper Wallet](https://github.com/anon-br/ergo-paper-wallet) also provides the same key on the printed wallet.

It would be nice for these users could securely track their balances through this feature.

**Comment by MrStahlfelge** [comment]
- [ ] Add xpubkey to db scheme
- [ ] Make add read only screen support using xpubkey (and save it for later use)
- [ ] Support deriving addresses from xpubkey
- [ ] Add way to show xpubkey in wallet config screen
