### ISSUE TITLE
Box selection inaccurate when there are unconfirmed transactions (transaction is discarded)

### ISSUE THREAD

**Issue by MrStahlfelge** [ergoplatform/ergo-wallet-app#5]
Steps to  reproduce:

* Send an amount of ERGs to any address
* While the transaction is not confirmed, do it again

The second transaction is discarded because it selected the same unspent boxes to spend.

Another feature that would be good to have is a way to cancel transactions waiting on the mempool.

**Comment by MrStahlfelge** [comment]
> You can generate tx with the wallet and use /transactions/check to fully check the tx as mempool does (after accepting tx asynchronously)

**Comment by esot321c** [comment]
Feature request which is related to this issue: Batch transactions. IE i can sent more than one transaction to chain before the previous approves. So if i have 3 transactions to do, i don't have to wait 2 to 5 minutes from the 1st to then send the 2nd manually. Is this a security issue or something potentially plausible?

It could look like this: 

- User wants to send 3 transactions
- User sends transaction 1, approves it, wallet sends it to chain immediately. 
- User sets up transaction 2, approves it, wallet asks "do you want to cache this transaction to send after the current unprocessed transaction?" or something of this nature, with a link to explain in detail what will be happening behind the scenes. 
- User sets up transaction 3, approves it, wallet caches
- Transaction 1 completes, user is notified, transaction 2 starts (user could be prompted to cancel or continue perhaps?)
- transaction 2 completes, wallet sends 3 with a prompt

The current functionality is that the user has to actually keep an eye on the blockchain explorer until their first transaction is approved before sending their second. From a UX perspective, it's not ideal, and many users will not understand why this is this case, or know to check block explorer.
