### ISSUE TITLE
Easier handling when sending tokens

### ISSUE THREAD

**Issue by S0methinguseful** [ergoplatform/ergo-wallet-app#51]
As a user, when I send tokens, I need the application to automatically enter the minimum ERG required to send a token, in order to simplify the process.  If required I can amend the ERG that is sent.

![tokens](https://user-images.githubusercontent.com/93325375/139251979-6f869eb5-eddb-443d-86e7-46beb0e14eb3.png)

**Comment by MrStahlfelge** [comment]
This will be done slightly different: 

* When a token is added, the amount field stays empty, but if it is not filled by the user, it does not raise a warning but instead minimum amount is used

Also subject to change when this is done:
* When a unique token is added (no decimals and available amount 1), the amount is automatically set to 1 and can't be changed. When remove is clicked for such a token, the amount is not emptied but the token is removed. This saves some taps when handling NFT
* When a token is added and the amount is not set, the amount field gains focus automatically
